import turtle as t
import time
t.setup (500,500)
t.speed (0)
t.bgcolor ("white")
t.shape ("turtle")
def rec(l,w,f):
  t.pendown()
  if f == True:
    t.begin_fill()
  t.forward(l)
  t.right(90)
  t.forward(w)
  t.right(90)
  t.forward(l)
  t.right(90)
  t.forward(w)
  if f == True:
    t.end_fill()
def drawRound(size,filled):
  t.pendown()
  if filled == True:
    t.begin_fill()
  t.setheading(180)
  t.circle(size,360)
  if filled ==True:
    t.end_fill()
def head():
  t.color("blue","blue") 
  t.penup()
  t.goto(0, 100)
  drawRound(75,True)
  t.color("white","white")
  t.penup()
  t.goto(0,72) #goto tells the position on basis of x,y coordinate.
  drawRound(60,True)
def eyes():
  t.color("black","white")
  t.penup()
  t.goto(-15,80) 
  drawRound(17,True)
  t.color("black","white")
  t.penup()
  t.goto(19,80)
  drawRound(17,True)
  t.color("black","black")
  t.penup()
  t.goto(-8,70)
  drawRound(6,True)
  t.color("white","white")
  t.penup()
  t.goto(-8,66)
  drawRound(2,True)
  t.color("black","black")
  t.penup()
  t.goto(13,70)
  drawRound(6,True)
  t.color("white","white")
  t.penup()
  t.goto(12,66)
  drawRound(2,True)
def nose():
  t.color("red","red")
  t.penup()
  t.goto(0,40)
  drawRound(7,True)
def mouth():
  t.color("black","black")
  t.penup()
  t.goto(-30,-30)
  t.pendown()
  t.setheading(-27)
  t.circle(70,55)
  t.penup()
  t.goto(0,26)
  t.pendown()
  t.goto(0,-25)
def whiskers():
  t.color("black","black")
  t.penup()
  t.goto(10,5)
  t.pendown()
  t.goto(-40,5)
  t.penup()
  t.goto(10,5)
  t.pendown()
  t.goto(40,5)
  t.penup()
  t.goto(-10,15)
  t.pendown()
  t.goto(-40,20)
  t.penup()
  t.goto(10,15)
  t.pendown()
  t.goto(40,20)
  t.penup()
  t.goto(-10,-5)
  t.pendown()
  t.goto(-40,-10)
  t.penup()
  t.goto(10,-5)
  t.pendown()
  t.goto(40,-10)
def body():
  t.color("blue","blue")
  t.penup()
  t.goto(0,-50)
  t.pendown()
  drawRound(70,True)
  t.color("white","white")
  drawRound(50,True)


head()
eyes()
nose()
mouth()
whiskers()
body()
time.sleep(1000)